name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 0 * * *"  # Chạy tự động mỗi ngày vào 00:00 UTC
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  update-readme:
    name: Update WakaTime Data in README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install WakaTime GitHub Action
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: "waka"  # Đảm bảo trùng với README.md
          TIME_RANGE: "7"  # Lấy dữ liệu trong 7 ngày gần nhất
          SHOW_TITLE: "True"
          SHOW_TIME: "True"
          SHOW_TOTAL: "True"
          SHOW_MASKED_TIME: "False"
          STOP_AT_OTHER: "True"
          COMMIT_MESSAGE: "Updated WakaTime stats"
          TARGET_BRANCH: "main"
          TARGET_PATH: "README.md"
